spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shopin?createDatabaseIfNotExist=true
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            connectionTimeout: 10000
            connectionTestQuery: SELECT 1 FROM DUAL
            maxLifetime: 1800000
            minimumIdle: 10
            maximumPoolSize: 10
            idleTimeout: 0
            poolName: ShopinPool
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        properties:
            javax:
                persistence:
                    validation:
                        mode: none
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
                globally_quoted_identifiers: true
        hibernate:
            ddl-auto: none
            connection:
                provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    mail:
        host: localhost
        port: 25
        user: none
        password: create
    thymeleaf:
        prefix: classpath:/templates/
    #profiles:
    #    active: development

server:
    error:
        whitelabel:
            enabled: false

# custom settings
org:
    security:
        url:
            activate: http://localhost:8080/activate/
            newpassword: http://localhost:8080/newpassword/
    error:
        code: 1000
    password:
        extralength: 2
    resources:
        static: classpath:/artifacts/

recaptcha:
    validation:
        secretKey: 6LfSXw0UAAAAAHhqL0VfFsDo23-8Y8u6gD_PQrOk

number:
    in:
        range: ${random.int[11111111,99999999]}
    rememberme:
        seconds: 7200

products:
    per:
        page: 6
    page:
        cache: 5
    cart:
        maxsize: 100
        maxcost: 10000
    image:
        root: http://localhost:8080/images

admin:
    email: admin@shopin.org
    password: shopin
app:
    email: shopin@org.com